### ISSUE TITLE
Error lsp cannot start

### ISSUE THREAD

**Issue by fajarsusilo** [sublimelsp/LSP-Dart#2]
How to fix lsp not start. in the console error notice "File "/home/fajarsusilo/.config/sublime-text-3/Installed Packages/LSP-Dart.sublime-package/plugin.py", line 2, in <module>
ImportError: cannot import name AbstractPlugin"

![Screenshot_2021-03-31_00-14-23](https://user-images.githubusercontent.com/45891576/113028959-13f79480-91b6-11eb-8f11-fc4ead598b7a.png)

**Comment by novan** [comment]
I have an issue starting LSP-Dart on ST4. I'm not sure if it's LSP-Dart's issue or LSP's issue. Here's the detail:

```
reloading settings Packages/User/LSP-Dart.sublime-settings
Unable to start subprocess for dart
Traceback (most recent call last):
  File "/Users/novan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 326, in start_async
    transport = create_transport(transport_config, cwd, session)
  File "/Users/novan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 207, in create_transport
    process = start_subprocess()
  File "/Users/novan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 196, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "/Users/novan/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 277, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1351, in _execute_child
IndexError: list index out of range```

**Comment by rwols** [comment]
You have a “dart” configuration enabled in LSP.sublime-settings. Remove that configuration in favor of letting LSP-Dart taking care of the startup config.

**Comment by novan** [comment]
You're right. There's a "dart" configuration in LSP.sublime-settings but I can't remove it. So, I add this line under `clients` on the user setting for LSP.sublime-settings and it works. Thanks!

```
"dart": {},
```

**Comment by rwols** [comment]
This looks resolved.
