### ISSUE TITLE
Can not start on sublime 4

### ISSUE THREAD

**Issue by navidshad** [sublimelsp/LSP-Dart#3]
Hi, I use sublime 4, after installing I get this error

```
reloading python 3.3 plugin LSP-Dart.plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Navid\AppData\Roaming\Sublime Text\Installed Packages\LSP-Dart.sublime-package\plugin.py", line 1, in <module>
ImportError: No module named 'LSP'
```

**Comment by rwols** [comment]
Did you install the LSP package?

**Comment by navidshad** [comment]
Yes I have installed it through sublime package installer

**Comment by rwols** [comment]
Try restarting ST then.

**Comment by rwols** [comment]
Correct operation of these helper packages depend on load order. If you installed LSP-Dart first, and then LSP, you need to either reload with AutomaricPackageReloader, or restart ST.

**Comment by navidshad** [comment]
Oh I thought LSP module being internalized in sublime!
I have installed LSP separately, the problem resolved.

thanks

**Comment by rwols** [comment]
Glad to hear you got it sorted out.
